version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      # Check for updates on the first Sunday of every month, 8PM UTC
      interval: "cron"
      cronjob: "0 20 * * sun#1"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"

  - package-ecosystem: "pip"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "dependencies"
